<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Orleans.Client" />
    <PackageReference Include="Microsoft.Orleans.Clustering.AdoNet" />
    <PackageReference Include="Microsoft.Orleans.Persistence.AdoNet" />
    <PackageReference Include="Microsoft.Orleans.Sdk" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleVotingSystem.Polls\SimpleVotingSystem.Polls.csproj" />
    <ProjectReference Include="..\SimpleVotingSystem.ServiceDefaults\SimpleVotingSystem.ServiceDefaults.csproj" />
  </ItemGroup>
  
</Project>
