<Project Sdk="Aspire.AppHost.Sdk/13.1.0">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>beac1fab-b54f-4c30-867b-d9d1fe80c6b3</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Orleans" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
    <PackageReference Include="Aspire.Microsoft.Data.SqlClient" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimpleVotingSystem.Api\SimpleVotingSystem.Api.csproj" />
    <ProjectReference Include="..\SimpleVotingSystem.Silo\SimpleVotingSystem.Silo.csproj" />
  </ItemGroup>

</Project>
